const SCREENS_NAME = {
  // Scene name
  WAREHOUSE: 'WAREHOUSE_SCREEN',
  LIST_STAFF: 'LIST_STAFF_SCREEN',
  SAVED_IDIOMS: 'SAVED_IDIOMS_SCREEN',
  SEARCH: 'SEARCH_SCREEN',
  CATEGORY: 'CATEGORY_SCREEN',
  DUMMY: 'DUMMY_SCREEN',
  HOME: 'HOME_SCREEN',
  GET_START: 'GET_START_SCREEN',
  PROFILE: 'PROFILE_SCREEN',
  SETTINGS: 'SETTINGS_SCREEN',
  MAIN: 'MainScreen',
  SIGN_IN: 'SignInScreen',
};

export default SCREENS_NAME;
